export const registroAtividadeSchema = {
  title: 'Registro de Atividade Schema',
  type: 'object',
  required: [
    'id',
    'alunoId',
    'disciplinaId',
    'titulo',
    'descricao',
    'status',
    'nota',
    'feedback',
    'dataEntrega',
    'createdAt',
    'updatedAt',
  ],
  properties: {
    id: { type: 'string' },
    alunoId: { type: 'string' },
    disciplinaId: { type: 'string' },
    titulo: { type: 'string' },
    descricao: { type: 'string' },
    status: { type: 'string' },
    nota: { type: ['number', 'null'] },
    feedback: { type: ['string', 'null'] },
    dataEntrega: { type: 'string' },
    createdAt: { type: 'string' },
    updatedAt: { type: 'string' },
  },
};